# Generated by Django 4.2.7 on 2025-12-14 04:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('bhw_verified', 'BHW Verified'), ('mswdo_approved', 'MSWDO Approved'), ('scheduled', 'Scheduled'), ('claimed', 'Claimed'), ('denied', 'Denied')], default='pending', max_length=50)),
                ('form_data', models.JSONField(default=dict)),
                ('bhw_verified_at', models.DateTimeField(blank=True, null=True)),
                ('bhw_notes', models.TextField(blank=True, null=True)),
                ('mswdo_approved_at', models.DateTimeField(blank=True, null=True)),
                ('mswdo_notes', models.TextField(blank=True, null=True)),
                ('denial_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'applications',
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('classification', models.JSONField(default=list)),
                ('requirements', models.JSONField(default=list)),
                ('program_type', models.CharField(choices=[('cash_assistance', 'Cash Assistance'), ('medical', 'Medical'), ('educational', 'Educational'), ('livelihood', 'Livelihood')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'programs',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField()),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('user_type', models.CharField(choices=[('beneficiary', 'Beneficiary'), ('admin', 'Admin'), ('bhw', 'BHW'), ('mswdo', 'MSWDO')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='ReleaseSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('release_date', models.DateField()),
                ('release_time', models.TimeField(blank=True, null=True)),
                ('venue', models.CharField(max_length=255)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='release_schedule', to='core.application')),
                ('claimed_by_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.user')),
            ],
            options={
                'db_table': 'release_schedules',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('type', models.CharField(choices=[('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error')], default='info', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.application')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.user')),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('classification', models.CharField(choices=[('senior_citizen', 'Senior Citizen'), ('pwd', 'PWD'), ('solo_parent', 'Solo Parent')], max_length=50)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('pwd_id_number', models.CharField(blank=True, max_length=255, null=True)),
                ('guardian_name', models.CharField(blank=True, max_length=255, null=True)),
                ('guardian_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('guardian_relationship', models.CharField(blank=True, max_length=255, null=True)),
                ('senior_id_url', models.CharField(blank=True, max_length=1024, null=True)),
                ('psa_url', models.CharField(blank=True, max_length=1024, null=True)),
                ('postal_id_url', models.CharField(blank=True, max_length=1024, null=True)),
                ('voters_id_url', models.CharField(blank=True, max_length=1024, null=True)),
                ('national_id_url', models.CharField(blank=True, max_length=1024, null=True)),
                ('medical_cert_url', models.CharField(blank=True, max_length=1024, null=True)),
                ('govt_id_url', models.CharField(blank=True, max_length=1024, null=True)),
                ('pwd_form_url', models.CharField(blank=True, max_length=1024, null=True)),
                ('barangay_cert_url', models.CharField(blank=True, max_length=1024, null=True)),
                ('death_cert_url', models.CharField(blank=True, max_length=1024, null=True)),
                ('medical_records_url', models.CharField(blank=True, max_length=1024, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiary', to='core.user')),
            ],
            options={
                'db_table': 'beneficiaries',
            },
        ),
        migrations.CreateModel(
            name='ApplicationDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(max_length=255)),
                ('document_url', models.CharField(max_length=1024)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.application')),
            ],
            options={
                'db_table': 'application_documents',
            },
        ),
        migrations.AddField(
            model_name='application',
            name='beneficiary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='core.beneficiary'),
        ),
        migrations.AddField(
            model_name='application',
            name='bhw_verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_applications', to='core.user'),
        ),
        migrations.AddField(
            model_name='application',
            name='mswdo_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_applications', to='core.user'),
        ),
        migrations.AddField(
            model_name='application',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='core.program'),
        ),
        migrations.CreateModel(
            name='BHWAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('barangay', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bhw_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bhw_assignments', to='core.user')),
            ],
            options={
                'db_table': 'bhw_assignments',
                'unique_together': {('bhw_user', 'barangay')},
            },
        ),
    ]
