# Generated by Django 5.0.6 on 2025-12-14 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='disability_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
