# Generated by Django 5.0.6 on 2025-12-17 14:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_beneficiary_disability_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeceasedReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=50, null=True)),
                ('nationality', models.CharField(blank=True, max_length=100, null=True)),
                ('email_address', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('beneficiary_name', models.CharField(max_length=255)),
                ('beneficiary_barangay', models.CharField(max_length=255)),
                ('date_time_of_death', models.DateTimeField()),
                ('cause_of_death', models.TextField(blank=True, null=True)),
                ('source_of_information', models.CharField(blank=True, choices=[('family', 'Family'), ('hospital', 'Hospital'), ('barangay', 'Barangay')], max_length=20, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_deceased_reports', to='core.user')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deceased_reports', to='core.user')),
            ],
            options={
                'db_table': 'deceased_reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
