# Generated by Django 5.0.6 on 2025-12-17 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_deceasedreport'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deceasedreport',
            options={},
        ),
        migrations.RenameField(
            model_name='deceasedreport',
            old_name='email_address',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='deceasedreport',
            name='confirmed_at',
        ),
        migrations.RemoveField(
            model_name='deceasedreport',
            name='confirmed_by',
        ),
        migrations.RemoveField(
            model_name='deceasedreport',
            name='status',
        ),
        migrations.RemoveField(
            model_name='deceasedreport',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='deceasedreport',
            name='user',
        ),
        migrations.AlterField(
            model_name='deceasedreport',
            name='beneficiary_barangay',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='deceasedreport',
            name='beneficiary_name',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='deceasedreport',
            name='date_time_of_death',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deceasedreport',
            name='full_name',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='deceasedreport',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='deceasedreport',
            name='nationality',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='deceasedreport',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='deceasedreport',
            name='source_of_information',
            field=models.CharField(blank=True, choices=[('family', 'Family'), ('hospital', 'Hospital'), ('barangay', 'Barangay')], max_length=50, null=True),
        ),
    ]
